/*
 * Copyright 2004-present Facebook. All Rights Reserved.
 */
package com.facebook.swift.service.scribe;

/**
 * Autogenerated by Thrift Compiler (0.8.0)
 * <p/>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */

public enum ResultCode implements org.apache.thrift.TEnum {
  OK(0),
  TRY_LATER(1);

  private final int value;

  private ResultCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   *
   * @return null if the value is not found.
   */
  public static ResultCode findByValue(int value) {
    switch (value) {
      case 0:
        return OK;
      case 1:
        return TRY_LATER;
      default:
        return null;
    }
  }
}
